baseURL = "https://asylog.github.io/"
title = "asylog"

# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true
[markup]
[markup.highlight]
style = 'catppuccin-latte'

enableEmoji = true
enableRobotsTXT = true

copyright = 'WTFPL'


# [menus]
# [[menus.main]]
#   name = 'readings'
#   pageRef = 'readings'
# [[menus.main]]
# name = 'rss'
# url = '/index.xml'

[outputs]
home = ['html', 'rss']
section = ['html']
taxonomy = ['html']
term = ['html']

[params]
mode = "light"
subtitle = "excerpts and reflections / deviant ideas and intrusive thoughts"
mathjax = true
copyrightUrl = "https://www.wtfpl.net/"
noaiUrl = "https://www.no-ai-icon.com/statement/?url=(asylog.github.io)"

[frontmatter]
date = ["lastmod", "date"]

[services.rss]
limit = 3

[permalinks]
writings = "/:section/:year/:slug/"
readings = "/:section/:year/:slug/"

[taxonomies]
series = 'series'
